# set the base image
FROM alpine
MAINTAINER lnoisome
LABEL version="1.0"
LABEL description="First image with Dockerfile."
RUN apk update
RUN apk add vim
ENTRYPOINT vim

#https://www.sitepoint.com/how-to-build-an-image-with-the-dockerfile/
#https://docs.docker.com/engine/reference/builder/#/maintainer

#docker run -it <image>
